model_list:
  # Configured via setup script
  - model_name: zibaldone-model
    litellm_params:
      model: openai/meta-llama-3.1-8b-instruct
      api_base: "http://localhost:1234/v1"
      api_key: "any-string"

  # Fallback
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
